apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretreadernew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretreadernew
  template:
    metadata:
      labels:
        name: secretreadernew
        app: secretreadernew
    spec:
      containers:
      - name: api-key
        image: karthequian/secretreader:latest
        env:
        - name: apikey
          value: api_key
