apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretreader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretreader
  template:
    metadata:
      labels:
        name: secretreader
        app: secretreader
    spec:
      containers:
      - name: secretreader
        image: karthequian/secretreader:latest
        env:
        - name: apikey
          value: api_key
