apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretreader3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretreader3
  template:
    metadata:
      labels:
        name: secretreader3
        app: secretreader3
    spec:
      containers:
      - name: api-key
        image: karthequian/secretreader:latest
        env:
        - name: apikey2
          value: api-key
